### ISSUE TITLE
Week 9 indiviudal college board videos

### ISSUE THREAD

**Issue by KylieScharf** [KylieScharf/newportfolio#3]
Include 3 college board topics in your video and have 1 topic ready for live grading the following week (4 college board topics total to cover)

| Team Member Name        | Video     | Average Score from Score Card Below |
| -------------           | -------------           | -----------------------                         |
| Kylie      | [video](https://watch.screencastify.com/v/KyFzK6tzMuTcDltXl4s3) |   6/6 | 
| Khushi      | [video](https://watch.screencastify.com/v/vSaLdYxuA6DAHJWD3VYg) |  6/6   | 
| Daniel     | [video](https://watch.screencastify.com/v/rVadlEkqezgLjtjrXvVI) | 6/6 |
| Hamza    | (https://youtu.be/P3sScdDjNCI) | 6/6 | 
| Kevin     | [video](https://www.loom.com/share/df7f4361e36a4cf1a3f48238bc5deb69) | 5.8/6 |

- [x] kylie's comments on team members' videos: [link](https://github.com/KylieScharf/newportfolio/issues/3#issuecomment-949872137)
- [x] khushi's comments on team members' videos: [link](https://github.com/KylieScharf/newportfolio/issues/3#issuecomment-949873589)
- [x] kevin's comments on team members' videos: [link](https://github.com/KylieScharf/newportfolio/issues/3#issuecomment-949873470)
- [x] hamza's comments on team members' videos: [link](https://github.com/KylieScharf/newportfolio/issues/3#issuecomment-949872223)
- [x] daniel's comments on team members' videos: [link](https://github.com/KylieScharf/newportfolio/issues/3#issuecomment-949879506)
- [x] score card showing each score for scores in table above: [link](https://github.com/KylieScharf/newportfolio/issues/3#issuecomment-951313963)

**Comment by AkhilNandhakumar** [comment]
### Akhil's Overall Score of Kevin: **6.5/8**

**Video Topic Scores:**
Program Design/Purpose: Wireframe example shown was very nice and easy to follow, the explanation of the website purpose and how it would be designed connected well to college-board, and the PBL relevance was spot on, it was fitting to your website purpose and also connected to college-board!**2/2**

Data Abstraction: The example shown was good, but the explanation of the data abstraction was a bit weak, and the code shown wasn't super connected to PBL, but was instead work from a minilab.  **1.5/2**

Switching ASCII to Unicode (Mathematical Expressions?) : The connection to college-board was a bit difficult to understand. It wasn't specified whether the conversion of Unicode to ASCII fell under Design, Mathematical Expressions, Variables/Assignments, or any other college board topic since all parts of code was generally overviewed in the Tour of Code/runtime. Explanation seemed a bit weak**1.25/2**

**Glows:**
I liked the explanation of the first topic Purpose/Program design, I thought the wireframe/flow chart design was cool and creative. The pacing of the video was also slow enough to understand everything you were saying. I also liked your runtime demo which was easy to follow.

**Grows:**
The video was a bit short even though the video was slow paced, I feel like you could've included a bit more info/explanations. I also think that your examples could've been more PBL related, rather than Minilab work like the Unicode/Ascii conversion and greet code.

Comment score: **1.75/2**
You commented on all your peers videos, and the comments were ok, they could've been a bit more specific by specifying certain sections or aspects of each video. Overall really good job!
